/**
 * Bazzar Grocery Mart — Seed Script
 * Clears & repopulates bazzar_db with grocery data.
 * Run: node seed.js
 * Requires: npm install mongodb bcryptjs
 */

async function main() {
  let MongoClient, bcrypt;
  try { MongoClient = require('mongodb').MongoClient; } catch(e) {
    require('child_process').execSync('npm install mongodb', { cwd: __dirname, stdio: 'inherit' });
    MongoClient = require('mongodb').MongoClient;
  }
  try { bcrypt = require('bcryptjs'); } catch(e) {
    require('child_process').execSync('npm install bcryptjs', { cwd: __dirname, stdio: 'inherit' });
    bcrypt = require('bcryptjs');
  }

  console.log('\n🌱 Bazzar Grocery Seed — Clearing & Repopulating bazzar_db\n' + '='.repeat(60));

  const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/bazzar_db';
  const client = new MongoClient(MONGO_URI);
  await client.connect();
  const db = client.db();
  console.log(`\n✅ Connected to: ${MONGO_URI}`);

  const adminHash  = await bcrypt.hash('Admin@1234', 12);
  const buyerHash  = await bcrypt.hash('Buyer@1234', 12);
  const sellerHash = await bcrypt.hash('Seller@1234', 12);

  // ── USERS ────────────────────────────────────────────────────────────────
  console.log('\n👤 Users...');
  await db.collection('users').deleteMany({});
  const res = await db.collection('users').insertMany([
    { firstName:'Admin',    lastName:'User',    email:'admin@bazzar.com',    password:adminHash,  role:'ADMIN',  phone:'9800000001', isActive:true, isEmailVerified:true, referralCode:'ADMIN001', refreshTokens:[], wishlist:[], createdAt:new Date(), updatedAt:new Date() },
    { firstName:'Ram',      lastName:'Sharma',  email:'ram@example.com',     password:buyerHash,  role:'BUYER',  phone:'9800000002', isActive:true, isEmailVerified:true, referralCode:'RAM001',   refreshTokens:[], wishlist:[], createdAt:new Date(), updatedAt:new Date() },
    { firstName:'HariBazar', lastName:'Store',  email:'seller1@bazzar.com',  password:sellerHash, role:'SELLER', phone:'9800000003', isActive:true, isEmailVerified:true, referralCode:'HARI001',  refreshTokens:[], wishlist:[], createdAt:new Date(), updatedAt:new Date() },
    { firstName:'FreshNepal',lastName:'Farms',  email:'seller2@bazzar.com',  password:sellerHash, role:'SELLER', phone:'9800000004', isActive:true, isEmailVerified:true, referralCode:'FRESH001', refreshTokens:[], wishlist:[], createdAt:new Date(), updatedAt:new Date() },
    { firstName:'OrganicKo', lastName:'Pasal',  email:'seller3@bazzar.com',  password:sellerHash, role:'SELLER', phone:'9800000005', isActive:true, isEmailVerified:true, referralCode:'ORG001',   refreshTokens:[], wishlist:[], createdAt:new Date(), updatedAt:new Date() },
  ]);
  const ids = Object.values(res.insertedIds);
  console.log(`  ✅ ${res.insertedCount} users`);

  // ── SELLERS ──────────────────────────────────────────────────────────────
  console.log('\n🏪 Sellers...');
  await db.collection('sellers').deleteMany({});
  const sres = await db.collection('sellers').insertMany([
    { userId:ids[2].toString(), storeName:'HariBazar',    description:'Your neighbourhood grocery store delivering fresh produce daily.', email:'seller1@bazzar.com', phone:'9800000003', logo:'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&q=80', banner:'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=900&q=85', category:'Grocery', address:{city:'Kathmandu',district:'Kathmandu',province:'Bagmati'}, status:'APPROVED', isVerified:true, rating:4.8, totalSales:980000, productCount:120, commissionRate:8, panNumber:'123456789', bankAccount:{bankName:'NIC Asia Bank',accountNumber:'1234567890',accountName:'HariBazar Pvt Ltd'}, createdAt:new Date(), updatedAt:new Date() },
    { userId:ids[3].toString(), storeName:'FreshNepal Farms', description:'Farm-fresh vegetables and fruits sourced directly from Nepali farmers.', email:'seller2@bazzar.com', phone:'9800000004', logo:'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=200&q=80', banner:'https://images.unsplash.com/photo-1518843875459-f738682238a6?w=900&q=85', category:'Fresh Produce', address:{city:'Lalitpur',district:'Lalitpur',province:'Bagmati'}, status:'APPROVED', isVerified:true, rating:4.7, totalSales:750000, productCount:85, commissionRate:8, panNumber:'987654321', bankAccount:{bankName:'Nabil Bank',accountNumber:'9876543210',accountName:'FreshNepal Farms Pvt Ltd'}, createdAt:new Date(), updatedAt:new Date() },
    { userId:ids[4].toString(), storeName:'OrganicKo Pasal', description:"Nepal's trusted organic grocery store. No chemicals, pure goodness.", email:'seller3@bazzar.com', phone:'9800000005', logo:'https://images.unsplash.com/photo-1506484381205-f7945653044d?w=200&q=80', banner:'https://images.unsplash.com/photo-1542838132-92c53300491e?w=900&q=85', category:'Organic', address:{city:'Bhaktapur',district:'Bhaktapur',province:'Bagmati'}, status:'APPROVED', isVerified:true, rating:4.6, totalSales:520000, productCount:60, commissionRate:8, panNumber:'456789123', bankAccount:{bankName:'Himalayan Bank',accountNumber:'4567891230',accountName:'OrganicKo Pasal Pvt Ltd'}, createdAt:new Date(), updatedAt:new Date() },
  ]);
  console.log(`  ✅ ${sres.insertedCount} sellers`);
  const sellerIds = Object.values(sres.insertedIds).map(i => i.toString());

  // ── CATEGORIES ───────────────────────────────────────────────────────────
  console.log('\n📂 Categories...');
  await db.collection('categories').deleteMany({});
  const cats = await db.collection('categories').insertMany([
    { name:'Fruits & Vegetables', slug:'fruits-vegetables', image:'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=700&q=80', description:'Fresh fruits and vegetables',       isActive:true, showInNav:true, sortOrder:1,  createdAt:new Date() },
    { name:'Dairy & Eggs',        slug:'dairy-eggs',        image:'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=700&q=80', description:'Milk, cheese, butter and eggs',    isActive:true, showInNav:true, sortOrder:2,  createdAt:new Date() },
    { name:'Grains & Pulses',     slug:'grains-pulses',     image:'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=700&q=80', description:'Rice, lentils, flour and more',   isActive:true, showInNav:true, sortOrder:3,  createdAt:new Date() },
    { name:'Meat & Fish',         slug:'meat-fish',         image:'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=700&q=80', description:'Fresh meat, poultry and seafood',  isActive:true, showInNav:true, sortOrder:4,  createdAt:new Date() },
    { name:'Snacks & Beverages',  slug:'snacks-beverages',  image:'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=700&q=80', description:'Chips, drinks and packaged foods', isActive:true, showInNav:true, sortOrder:5,  createdAt:new Date() },
    { name:'Spices & Condiments', slug:'spices-condiments', image:'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=700&q=80', description:'Spices, sauces and seasonings',   isActive:true, showInNav:true, sortOrder:6,  createdAt:new Date() },
    { name:'Bakery & Bread',      slug:'bakery-bread',      image:'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=700&q=80', description:'Fresh bread, cakes and pastries',  isActive:true, showInNav:true, sortOrder:7,  createdAt:new Date() },
    { name:'Oils & Ghee',         slug:'oils-ghee',         image:'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=700&q=80', description:'Cooking oils, ghee and butter',   isActive:true, showInNav:true, sortOrder:8,  createdAt:new Date() },
  ]);
  const catIds = Object.values(cats.insertedIds);
  console.log(`  ✅ ${cats.insertedCount} categories`);

  // ── SUBCATEGORIES ─────────────────────────────────────────────────────────
  console.log('\n📁 Subcategories...');
  const subCats = await db.collection('categories').insertMany([
    // Fruits & Vegetables
    { name:'Fresh Fruits',       slug:'fresh-fruits',       parentCategory:'fruits-vegetables', image:'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=700&q=80', description:'Seasonal and imported fresh fruits',    isActive:true, showInNav:false, sortOrder:1, createdAt:new Date() },
    { name:'Fresh Vegetables',   slug:'fresh-vegetables',   parentCategory:'fruits-vegetables', image:'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=700&q=80', description:'Farm-fresh vegetables harvested daily', isActive:true, showInNav:false, sortOrder:2, createdAt:new Date() },
    { name:'Organic Produce',    slug:'organic-produce',    parentCategory:'fruits-vegetables', image:'https://images.unsplash.com/photo-1542838132-92c53300491e?w=700&q=80', description:'Certified organic fruits and vegetables', isActive:true, showInNav:false, sortOrder:3, createdAt:new Date() },
    // Dairy & Eggs
    { name:'Milk & Cream',       slug:'milk-cream',         parentCategory:'dairy-eggs',        image:'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=700&q=80', description:'Fresh milk, cream and curd',              isActive:true, showInNav:false, sortOrder:1, createdAt:new Date() },
    { name:'Cheese & Paneer',    slug:'cheese-paneer',      parentCategory:'dairy-eggs',        image:'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=700&q=80', description:'Paneer, cheese and dairy solids',         isActive:true, showInNav:false, sortOrder:2, createdAt:new Date() },
    { name:'Eggs',               slug:'eggs',               parentCategory:'dairy-eggs',        image:'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=700&q=80', description:'Fresh eggs from local farms',             isActive:true, showInNav:false, sortOrder:3, createdAt:new Date() },
    // Grains & Pulses
    { name:'Rice & Cereals',     slug:'rice-cereals',       parentCategory:'grains-pulses',     image:'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=700&q=80', description:'Basmati, beaten rice and cereals',         isActive:true, showInNav:false, sortOrder:1, createdAt:new Date() },
    { name:'Dal & Lentils',      slug:'dal-lentils',        parentCategory:'grains-pulses',     image:'https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=700&q=80', description:'Masoor, moong, chana and other lentils',   isActive:true, showInNav:false, sortOrder:2, createdAt:new Date() },
    { name:'Flour & Atta',       slug:'flour-atta',         parentCategory:'grains-pulses',     image:'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=700&q=80', description:'Wheat atta, maida and other flours',       isActive:true, showInNav:false, sortOrder:3, createdAt:new Date() },
    // Meat & Fish
    { name:'Chicken',            slug:'chicken',            parentCategory:'meat-fish',         image:'https://images.unsplash.com/photo-1604503468506-a8da13d11e18?w=700&q=80', description:'Fresh whole and cut chicken',              isActive:true, showInNav:false, sortOrder:1, createdAt:new Date() },
    { name:'Mutton & Goat',      slug:'mutton-goat',        parentCategory:'meat-fish',         image:'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=700&q=80', description:'Fresh goat and mutton cuts',               isActive:true, showInNav:false, sortOrder:2, createdAt:new Date() },
    { name:'Fish & Seafood',     slug:'fish-seafood',       parentCategory:'meat-fish',         image:'https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=700&q=80', description:'Fresh water and sea fish',                 isActive:true, showInNav:false, sortOrder:3, createdAt:new Date() },
    { name:'Eggs & Poultry',     slug:'eggs-poultry',       parentCategory:'meat-fish',         image:'https://images.unsplash.com/photo-1569288052389-dac9b0ac9eac?w=700&q=80', description:'Duck eggs and other poultry products',     isActive:true, showInNav:false, sortOrder:4, createdAt:new Date() },
    // Snacks & Beverages
    { name:'Snacks & Chips',     slug:'snacks-chips',       parentCategory:'snacks-beverages',  image:'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=700&q=80', description:'Chips, noodles and packaged snacks',       isActive:true, showInNav:false, sortOrder:1, createdAt:new Date() },
    { name:'Beverages & Drinks', slug:'beverages-drinks',   parentCategory:'snacks-beverages',  image:'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=700&q=80', description:'Juices, soft drinks and flavoured water',  isActive:true, showInNav:false, sortOrder:2, createdAt:new Date() },
    { name:'Tea & Coffee',       slug:'tea-coffee',         parentCategory:'snacks-beverages',  image:'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=700&q=80', description:'Premium teas, instant coffee and blends',  isActive:true, showInNav:false, sortOrder:3, createdAt:new Date() },
    // Spices & Condiments
    { name:'Spices',             slug:'spices',             parentCategory:'spices-condiments', image:'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=700&q=80', description:'Whole and ground spices for every dish',  isActive:true, showInNav:false, sortOrder:1, createdAt:new Date() },
    { name:'Sauces & Condiments',slug:'sauces-condiments',  parentCategory:'spices-condiments', image:'https://images.unsplash.com/photo-1605789538467-f715d58e03f9?w=700&q=80', description:'Ketchup, sauces and pickles',              isActive:true, showInNav:false, sortOrder:2, createdAt:new Date() },
    // Bakery & Bread
    { name:'Breads',             slug:'breads',             parentCategory:'bakery-bread',      image:'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=700&q=80', description:'Sliced breads, buns and rolls',            isActive:true, showInNav:false, sortOrder:1, createdAt:new Date() },
    { name:'Cakes & Pastries',   slug:'cakes-pastries',     parentCategory:'bakery-bread',      image:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=700&q=80', description:'Birthday cakes, pastries and sweets',      isActive:true, showInNav:false, sortOrder:2, createdAt:new Date() },
    { name:'Traditional Bakery', slug:'traditional-bakery', parentCategory:'bakery-bread',      image:'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=700&q=80', description:'Sel roti and other Nepali baked goods',    isActive:true, showInNav:false, sortOrder:3, createdAt:new Date() },
    // Oils & Ghee
    { name:'Cooking Oils',       slug:'cooking-oils',       parentCategory:'oils-ghee',         image:'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=700&q=80', description:'Mustard, sunflower, coconut and olive oil',isActive:true, showInNav:false, sortOrder:1, createdAt:new Date() },
    { name:'Ghee & Butter',      slug:'ghee-butter',        parentCategory:'oils-ghee',         image:'https://images.unsplash.com/photo-1593759608142-e976bfe89e4e?w=700&q=80', description:'Pure cow ghee and cooking butter',         isActive:true, showInNav:false, sortOrder:2, createdAt:new Date() },
  ]);
  console.log(`  ✅ ${subCats.insertedCount} subcategories`);

  // ── BANNERS ──────────────────────────────────────────────────────────────
  console.log('\n🖼️  Banners...');
  await db.collection('banners').deleteMany({});
  await db.collection('banners').insertMany([
    { title:'Fresh From The', subtitle:'Farm To You', description:'Handpicked fruits and vegetables delivered fresh to your doorstep across Nepal.', cta:'Shop Fresh', ctaLink:'/products?category=fruits-vegetables', image:'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=900&q=85', accentColor:'#22c55e', eyebrow:"Nepal's #1 Grocery Mart", badge:'🥦 Farm Fresh Daily', order:0, isActive:true, createdAt:new Date() },
    { title:'Daily Dairy',    subtitle:'Essentials', description:'Pure milk, fresh paneer, dahi and eggs from trusted local farms.', cta:'Shop Dairy', ctaLink:'/products?category=dairy-eggs', image:'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=900&q=85', accentColor:'#f59e0b', eyebrow:'Morning Essentials', badge:'🥛 100% Pure', order:1, isActive:true, createdAt:new Date() },
    { title:'Stock Up On',    subtitle:'Pantry Staples', description:'Premium quality rice, dal, atta and spices at the best prices.', cta:'Shop Pantry', ctaLink:'/products?category=grains-pulses', image:'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=900&q=85', accentColor:'#f97316', eyebrow:'Pantry Essentials', badge:'🌾 Best Price Guaranteed', order:2, isActive:true, createdAt:new Date() },
  ]);
  console.log('  ✅ 3 banners');

  // ── PRODUCTS ─────────────────────────────────────────────────────────────
  console.log('\n🛒 Products...');
  await db.collection('products').deleteMany({});
  const [s1, s2, s3] = sellerIds;
  const [fvId, deId, gpId, mfId, sbId, scId, bbId, ogId] = catIds;

  const prods = [
    // ── Fruits & Vegetables ─────────────────────────────────────────────
    { name:'Organic Tomatoes (1 kg)',      slug:'organic-tomatoes-1kg',      description:'Fresh, ripe tomatoes grown without pesticides. Perfect for curries and salads.', price:120,  salePrice:99,  images:['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=500&q=80'], category:fvId, subCategory:'fresh-vegetables', sellerId:s2, sellerName:'FreshNepal Farms', stock:200, sku:'FV-TOM-001', rating:4.7, reviewCount:312, isFeatured:true,  isActive:true, tags:['tomato','vegetables','organic'] },
    { name:'Green Spinach (500 g)',        slug:'green-spinach-500g',         description:'Tender leafy spinach packed with iron and vitamins. Harvested daily.', price:60,   salePrice:49,  images:['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&q=80'], category:fvId, subCategory:'fresh-vegetables', sellerId:s2, sellerName:'FreshNepal Farms', stock:150, sku:'FV-SPN-001', rating:4.6, reviewCount:189, isFeatured:false, isActive:true, tags:['spinach','leafy','vegetables'] },
    { name:'Himalayan Potatoes (2 kg)',    slug:'himalayan-potatoes-2kg',     description:'Premium hill-grown potatoes. Fluffy texture, ideal for aloo tarkari.', price:140,  salePrice:120, images:['https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=500&q=80'], category:fvId, subCategory:'fresh-vegetables', sellerId:s2, sellerName:'FreshNepal Farms', stock:300, sku:'FV-POT-001', rating:4.5, reviewCount:245, isFeatured:true,  isActive:true, tags:['potato','vegetables'] },
    { name:'Fresh Bananas (1 dozen)',      slug:'fresh-bananas-dozen',        description:'Sweet Nepali bananas, naturally ripened. Energy-rich and delicious.', price:80,   salePrice:69,  images:['https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&q=80'], category:fvId, subCategory:'fresh-fruits',      sellerId:s3, sellerName:'OrganicKo Pasal', stock:180, sku:'FV-BAN-001', rating:4.8, reviewCount:421, isFeatured:true,  isActive:true, tags:['banana','fruit'] },
    { name:'Red Apples (1 kg)',            slug:'red-apples-1kg',             description:'Crisp and juicy apples from Mustang. Sweet with a slight tang.', price:280,  salePrice:249, images:['https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=500&q=80'], category:fvId, subCategory:'fresh-fruits',      sellerId:s3, sellerName:'OrganicKo Pasal', stock:120, sku:'FV-APL-001', rating:4.9, reviewCount:198, isFeatured:true,  isActive:true, tags:['apple','fruit','mustang'] },
    { name:'Cauliflower (1 piece)',        slug:'cauliflower-1pc',            description:'Large, fresh cauliflower head. Great for sabji and soups.', price:75,   salePrice:65,  images:['https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=500&q=80'], category:fvId, subCategory:'fresh-vegetables', sellerId:s2, sellerName:'FreshNepal Farms', stock:90,  sku:'FV-CAU-001', rating:4.4, reviewCount:87,  isFeatured:false, isActive:true, tags:['cauliflower','vegetables'] },
    { name:'Cucumber (500 g)',             slug:'cucumber-500g',              description:'Cool and crunchy cucumbers, perfect for salads and raita.', price:50,   salePrice:40,  images:['https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=500&q=80'], category:fvId, subCategory:'fresh-vegetables', sellerId:s2, sellerName:'FreshNepal Farms', stock:160, sku:'FV-CUC-001', rating:4.3, reviewCount:134, isFeatured:false, isActive:true, tags:['cucumber','vegetables'] },
    { name:'Mango (1 kg)',                 slug:'mango-1kg',                  description:'Sweet Terai mangoes. Juicy and flavourful. Seasonal delight.', price:220,  salePrice:190, images:['https://images.unsplash.com/photo-1553279768-865429fa0078?w=500&q=80'], category:fvId, subCategory:'fresh-fruits',      sellerId:s3, sellerName:'OrganicKo Pasal', stock:100, sku:'FV-MNG-001', rating:4.8, reviewCount:276, isFeatured:true,  isActive:true, tags:['mango','fruit','seasonal'] },
    { name:'Carrot (1 kg)',                slug:'carrot-1kg',                 description:'Fresh orange carrots rich in beta-carotene. Great for curries and juices.', price:90,   salePrice:75,  images:['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=500&q=80'], category:fvId, subCategory:'fresh-vegetables', sellerId:s2, sellerName:'FreshNepal Farms', stock:140, sku:'FV-CAR-001', rating:4.5, reviewCount:102, isFeatured:false, isActive:true, tags:['carrot','vegetables'] },
    { name:'Green Capsicum (500 g)',       slug:'green-capsicum-500g',        description:'Crisp green bell peppers. Perfect for stir-fry and stuffed dishes.', price:85,   salePrice:70,  images:['https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=500&q=80'], category:fvId, subCategory:'fresh-vegetables', sellerId:s2, sellerName:'FreshNepal Farms', stock:110, sku:'FV-CAP-001', rating:4.4, reviewCount:78,  isFeatured:false, isActive:true, tags:['capsicum','vegetables'] },
    { name:'Organic Spinach (250 g)',      slug:'organic-spinach-250g',       description:'Certified organic baby spinach leaves. No pesticides, grown with natural compost.', price:75,  salePrice:65,  images:['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&q=80'], category:fvId, subCategory:'organic-produce',   sellerId:s3, sellerName:'OrganicKo Pasal', stock:120, sku:'FV-OSP-001', rating:4.8, reviewCount:143, isFeatured:false, isActive:true, tags:['organic','spinach','vegetables'] },
    { name:'Organic Mixed Salad Greens (200 g)', slug:'organic-salad-greens-200g', description:'Ready-to-eat organic salad mix with lettuce, arugula and micro greens.', price:110, salePrice:95, images:['https://images.unsplash.com/photo-1540420773420-3366772f4999?w=500&q=80'], category:fvId, subCategory:'organic-produce',   sellerId:s3, sellerName:'OrganicKo Pasal', stock:80,  sku:'FV-OSG-001', rating:4.7, reviewCount:89,  isFeatured:false, isActive:true, tags:['organic','salad','greens'] },

    // ── Dairy & Eggs ─────────────────────────────────────────────────────
    { name:'Fresh Cow Milk (1 litre)',     slug:'fresh-cow-milk-1l',          description:'Pure pasteurised cow milk from local farms. Collected fresh every morning.', price:95,   salePrice:90,  images:['https://images.unsplash.com/photo-1550583724-b2692b85b150?w=500&q=80'], category:deId, subCategory:'milk-cream',      sellerId:s1, sellerName:'HariBazar', stock:500, sku:'DE-MLK-001', rating:4.8, reviewCount:534, isFeatured:true,  isActive:true, tags:['milk','dairy'] },
    { name:'Dahi / Curd (500 g)',          slug:'dahi-curd-500g',             description:'Thick set curd made from whole milk. Creamy and mildly sour.', price:85,   salePrice:75,  images:['https://images.unsplash.com/photo-1571689936114-b89a7a8d2af6?w=500&q=80'], category:deId, subCategory:'milk-cream',      sellerId:s1, sellerName:'HariBazar', stock:200, sku:'DE-DAH-001', rating:4.5, reviewCount:178, isFeatured:false, isActive:true, tags:['dahi','curd','dairy'] },
    { name:'Fresh Paneer (200 g)',         slug:'fresh-paneer-200g',          description:'Soft homemade-style paneer made from full-cream milk. 200 g block.', price:160,  salePrice:145, images:['https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=500&q=80'], category:deId, subCategory:'cheese-paneer',   sellerId:s1, sellerName:'HariBazar', stock:120, sku:'DE-PNR-001', rating:4.6, reviewCount:211, isFeatured:true,  isActive:true, tags:['paneer','dairy','cheese'] },
    { name:'Butter (100 g)',               slug:'butter-100g',                description:'Creamy unsalted butter made from pasteurised cream. Great for cooking and baking.', price:120,  salePrice:110, images:['https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=500&q=80'], category:deId, subCategory:'cheese-paneer',   sellerId:s3, sellerName:'OrganicKo Pasal', stock:150, sku:'DE-BUT-001', rating:4.7, reviewCount:143, isFeatured:false, isActive:true, tags:['butter','dairy'] },
    { name:'Cheese Slices (200 g)',        slug:'cheese-slices-200g',         description:'Processed cheddar cheese slices. Ready to use in sandwiches and burgers.', price:250,  salePrice:225, images:['https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=500&q=80'], category:deId, subCategory:'cheese-paneer',   sellerId:s1, sellerName:'HariBazar', stock:80,  sku:'DE-CHS-001', rating:4.3, reviewCount:97,  isFeatured:false, isActive:true, tags:['cheese','dairy'] },
    { name:'Farm Eggs (12 pcs)',           slug:'farm-eggs-12pcs',            description:'Free-range hen eggs, rich in protein. Pack of 12.', price:240,  salePrice:220, images:['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=500&q=80'], category:deId, subCategory:'eggs',            sellerId:s1, sellerName:'HariBazar', stock:300, sku:'DE-EGG-001', rating:4.7, reviewCount:389, isFeatured:true,  isActive:true, tags:['eggs','protein','dairy'] },
    { name:'Quail Eggs (20 pcs)',          slug:'quail-eggs-20pcs',           description:'Tiny, nutritious quail eggs. High protein, great for appetisers and salads.', price:200, salePrice:180, images:['https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=500&q=80'], category:deId, subCategory:'eggs',            sellerId:s2, sellerName:'FreshNepal Farms', stock:90,  sku:'DE-QEG-001', rating:4.4, reviewCount:67,  isFeatured:false, isActive:true, tags:['quail eggs','eggs','protein'] },

    // ── Grains & Pulses ──────────────────────────────────────────────────
    { name:'Basmati Rice (5 kg)',          slug:'basmati-rice-5kg',           description:'Long-grain fragrant basmati rice. Perfect for biryani and pulao.', price:850,  salePrice:780, images:['https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&q=80'], category:gpId, subCategory:'rice-cereals',    sellerId:s1, sellerName:'HariBazar', stock:200, sku:'GP-RIC-001', rating:4.8, reviewCount:456, isFeatured:true,  isActive:true, tags:['rice','grains','basmati'] },
    { name:'Flattened Rice / Chiura (1 kg)', slug:'chiura-1kg',               description:'Traditional Nepali beaten rice. Ready to eat or cook. A cultural staple.', price:150,  salePrice:135, images:['https://images.unsplash.com/photo-1536304993881-ff86e0c9ef4c?w=500&q=80'], category:gpId, subCategory:'rice-cereals',    sellerId:s1, sellerName:'HariBazar', stock:250, sku:'GP-CHI-001', rating:4.7, reviewCount:267, isFeatured:true,  isActive:true, tags:['chiura','beaten rice','nepali'] },
    { name:'Red Lentils / Masoor Dal (1 kg)', slug:'masoor-dal-1kg',          description:'Split red lentils. Quick-cooking and high in protein. A Nepali kitchen staple.', price:180,  salePrice:165, images:['https://images.unsplash.com/photo-1515543237350-b3eea1ec8082?w=500&q=80'], category:gpId, subCategory:'dal-lentils',     sellerId:s1, sellerName:'HariBazar', stock:300, sku:'GP-DAL-001', rating:4.6, reviewCount:289, isFeatured:true,  isActive:true, tags:['dal','lentils','pulses'] },
    { name:'Black Chana (1 kg)',           slug:'black-chana-1kg',            description:'Wholesome black chickpeas. Great for chana masala and salads.', price:200,  salePrice:180, images:['https://images.unsplash.com/photo-1602253057119-44d745d9b860?w=500&q=80'], category:gpId, subCategory:'dal-lentils',     sellerId:s3, sellerName:'OrganicKo Pasal', stock:160, sku:'GP-CHA-001', rating:4.5, reviewCount:134, isFeatured:false, isActive:true, tags:['chana','chickpeas','pulses'] },
    { name:'Yellow Moong Dal (500 g)',     slug:'yellow-moong-dal-500g',      description:'Split yellow moong beans. Light, digestible and protein-rich.', price:130,  salePrice:115, images:['https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=500&q=80'], category:gpId, subCategory:'dal-lentils',     sellerId:s1, sellerName:'HariBazar', stock:220, sku:'GP-MOO-001', rating:4.6, reviewCount:198, isFeatured:false, isActive:true, tags:['moong','dal','pulses'] },
    { name:'Whole Wheat Atta (5 kg)',      slug:'whole-wheat-atta-5kg',       description:'Stone-ground whole wheat flour. Rich in fibre, ideal for roti and paratha.', price:650,  salePrice:600, images:['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&q=80'], category:gpId, subCategory:'flour-atta',      sellerId:s1, sellerName:'HariBazar', stock:180, sku:'GP-ATT-001', rating:4.7, reviewCount:312, isFeatured:false, isActive:true, tags:['atta','flour','wheat'] },
    { name:'Maida / All Purpose Flour (1 kg)', slug:'maida-1kg',              description:'Fine white all-purpose flour for baking, momos and bread making.', price:90,   salePrice:80,  images:['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=500&q=80'], category:gpId, subCategory:'flour-atta',      sellerId:s1, sellerName:'HariBazar', stock:300, sku:'GP-MAI-001', rating:4.5, reviewCount:167, isFeatured:false, isActive:true, tags:['maida','flour','baking'] },

    // ── Meat & Fish ──────────────────────────────────────────────────────
    { name:'Chicken Breast (500 g)',       slug:'chicken-breast-500g',        description:'Fresh boneless chicken breast. Lean protein, vacuum-sealed for freshness.', price:380,  salePrice:349, images:['https://images.unsplash.com/photo-1604503468506-a8da13d11e18?w=500&q=80'], category:mfId, subCategory:'chicken',         sellerId:s1, sellerName:'HariBazar', stock:80,  sku:'MF-CHK-001', rating:4.6, reviewCount:178, isFeatured:true,  isActive:true, tags:['chicken','meat','protein'] },
    { name:'Whole Chicken (1 kg)',         slug:'whole-chicken-1kg',          description:'Farm-fresh whole chicken, cleaned and dressed. Great for traditional recipes.', price:680,  salePrice:620, images:['https://images.unsplash.com/photo-1587593810167-a84920ea0781?w=500&q=80'], category:mfId, subCategory:'chicken',         sellerId:s1, sellerName:'HariBazar', stock:60,  sku:'MF-WCH-001', rating:4.5, reviewCount:145, isFeatured:false, isActive:true, tags:['chicken','whole','meat'] },
    { name:'Mutton / Khasi (500 g)',       slug:'mutton-khasi-500g',          description:'Fresh goat meat with bone. Tender cuts perfect for khasi ko masu.', price:850,  salePrice:820, images:['https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=500&q=80'], category:mfId, subCategory:'mutton-goat',     sellerId:s1, sellerName:'HariBazar', stock:50,  sku:'MF-MTN-001', rating:4.7, reviewCount:212, isFeatured:true,  isActive:true, tags:['mutton','khasi','meat'] },
    { name:'Fresh Rohu Fish (500 g)',      slug:'fresh-rohu-fish-500g',       description:'Fresh water rohu fish, cleaned and cut. A Nepali favourite for fish curry.', price:420,  salePrice:390, images:['https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=500&q=80'], category:mfId, subCategory:'fish-seafood',    sellerId:s2, sellerName:'FreshNepal Farms', stock:70,  sku:'MF-FSH-001', rating:4.4, reviewCount:98,  isFeatured:false, isActive:true, tags:['fish','rohu','seafood'] },
    { name:'Hilsa Fish (500 g)',           slug:'hilsa-fish-500g',            description:'Premium hilsa fish — the prized river catch. Rich in omega-3, full of flavour.', price:650, salePrice:599, images:['https://images.unsplash.com/photo-1544943910-4c1dc44aab44?w=500&q=80'], category:mfId, subCategory:'fish-seafood',    sellerId:s2, sellerName:'FreshNepal Farms', stock:40,  sku:'MF-HLS-001', rating:4.6, reviewCount:78,  isFeatured:false, isActive:true, tags:['hilsa','fish','seafood'] },
    { name:'Eggs Duck (6 pcs)',            slug:'duck-eggs-6pcs',             description:'Rich and flavourful duck eggs. Larger yolk, great for baking and cooking.', price:180,  salePrice:165, images:['https://images.unsplash.com/photo-1569288052389-dac9b0ac9eac?w=500&q=80'], category:mfId, subCategory:'eggs-poultry',    sellerId:s2, sellerName:'FreshNepal Farms', stock:90,  sku:'MF-DEG-001', rating:4.3, reviewCount:67,  isFeatured:false, isActive:true, tags:['duck eggs','eggs','protein'] },

    // ── Snacks & Beverages ───────────────────────────────────────────────
    { name:'Wai Wai Noodles (Pack of 5)', slug:'wai-wai-noodles-5pack',      description:"Nepal's most loved instant noodles. Crispy or cooked — always delicious.", price:125,  salePrice:110, images:['https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=500&q=80'], category:sbId, subCategory:'snacks-chips',    sellerId:s1, sellerName:'HariBazar', stock:500, sku:'SB-WAI-001', rating:4.9, reviewCount:678, isFeatured:true,  isActive:true, tags:['noodles','wai wai','snacks','nepali'] },
    { name:'Kurkure Masala (Pack of 3)', slug:'kurkure-masala-3pack',         description:'Crunchy corn puffs with tangy masala flavour. A family favourite snack.', price:90,   salePrice:80,  images:['https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&q=80'], category:sbId, subCategory:'snacks-chips',    sellerId:s1, sellerName:'HariBazar', stock:400, sku:'SB-KUR-001', rating:4.4, reviewCount:234, isFeatured:false, isActive:true, tags:['kurkure','snacks','chips'] },
    { name:'Lays Classic Salted (Pack of 3)', slug:'lays-classic-3pack',      description:'Light and crispy potato chips lightly salted. The classic snack everyone loves.', price:120, salePrice:105, images:['https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&q=80'], category:sbId, subCategory:'snacks-chips',    sellerId:s1, sellerName:'HariBazar', stock:350, sku:'SB-LAY-001', rating:4.5, reviewCount:198, isFeatured:false, isActive:true, tags:['lays','chips','snacks'] },
    { name:'Real Juice Orange (1 litre)', slug:'real-juice-orange-1l',        description:'100% fruit juice with no added sugar. Refreshing orange flavour.', price:160,  salePrice:145, images:['https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=500&q=80'], category:sbId, subCategory:'beverages-drinks', sellerId:s1, sellerName:'HariBazar', stock:200, sku:'SB-JUC-001', rating:4.5, reviewCount:213, isFeatured:false, isActive:true, tags:['juice','beverage','orange'] },
    { name:'Coca-Cola (1.5 litre)',       slug:'coca-cola-1-5l',              description:'The classic cola drink. Perfect for gatherings and celebrations.', price:130,  salePrice:120, images:['https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&q=80'], category:sbId, subCategory:'beverages-drinks', sellerId:s1, sellerName:'HariBazar', stock:300, sku:'SB-COK-001', rating:4.6, reviewCount:389, isFeatured:false, isActive:true, tags:['cola','beverage','soft drink'] },
    { name:'Himalayan Black Tea (100 g)', slug:'himalayan-black-tea-100g',    description:'Premium Ilam tea leaves from the hills of Nepal. Rich aroma and bold taste.', price:320,  salePrice:280, images:['https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&q=80'], category:sbId, subCategory:'tea-coffee',      sellerId:s3, sellerName:'OrganicKo Pasal', stock:150, sku:'SB-TEA-001', rating:4.8, reviewCount:312, isFeatured:true,  isActive:true, tags:['tea','ilam','beverage'] },
    { name:'Nescafe Classic (50 g)',      slug:'nescafe-classic-50g',         description:'Rich and aromatic instant coffee. Your perfect morning companion.', price:280,  salePrice:255, images:['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&q=80'], category:sbId, subCategory:'tea-coffee',      sellerId:s1, sellerName:'HariBazar', stock:180, sku:'SB-COF-001', rating:4.7, reviewCount:189, isFeatured:true,  isActive:true, tags:['coffee','nescafe','beverage'] },
    { name:'Green Tea Bags (25 pcs)',     slug:'green-tea-bags-25pcs',        description:'Light and refreshing green tea. Antioxidant-rich, great for health and digestion.', price:180, salePrice:160, images:['https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&q=80'], category:sbId, subCategory:'tea-coffee',      sellerId:s3, sellerName:'OrganicKo Pasal', stock:200, sku:'SB-GTB-001', rating:4.6, reviewCount:145, isFeatured:false, isActive:true, tags:['green tea','tea','health'] },

    // ── Spices & Condiments ──────────────────────────────────────────────
    { name:'Turmeric Powder (200 g)',      slug:'turmeric-powder-200g',       description:'Pure ground turmeric with high curcumin content. Vibrant colour and earthy flavour.', price:110,  salePrice:95,  images:['https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=500&q=80'], category:scId, subCategory:'spices',          sellerId:s3, sellerName:'OrganicKo Pasal', stock:250, sku:'SC-TUR-001', rating:4.7, reviewCount:298, isFeatured:false, isActive:true, tags:['turmeric','spice','haldi'] },
    { name:'Red Chilli Powder (200 g)',    slug:'red-chilli-powder-200g',     description:'Fiery red chilli powder with intense heat and colour. Sun-dried and freshly ground.', price:130,  salePrice:115, images:['https://images.unsplash.com/photo-1588514912908-c2a3b7680795?w=500&q=80'], category:scId, subCategory:'spices',          sellerId:s3, sellerName:'OrganicKo Pasal', stock:200, sku:'SC-RCP-001', rating:4.6, reviewCount:176, isFeatured:false, isActive:true, tags:['chilli','spice','red chilli'] },
    { name:'Garam Masala (100 g)',         slug:'garam-masala-100g',          description:'Authentic blend of whole spices. Adds warmth and depth to any dish.', price:160,  salePrice:140, images:['https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=500&q=80'], category:scId, subCategory:'spices',          sellerId:s3, sellerName:'OrganicKo Pasal', stock:180, sku:'SC-GAM-001', rating:4.8, reviewCount:234, isFeatured:true,  isActive:true, tags:['garam masala','spice','blend'] },
    { name:'Mustard Seeds (200 g)',        slug:'mustard-seeds-200g',         description:'Yellow mustard seeds for tempering. Pungent aroma, essential in Nepali cooking.', price:85,   salePrice:75,  images:['https://images.unsplash.com/photo-1599909533819-5cfc99278e08?w=500&q=80'], category:scId, subCategory:'spices',          sellerId:s3, sellerName:'OrganicKo Pasal', stock:160, sku:'SC-MUS-001', rating:4.4, reviewCount:98,  isFeatured:false, isActive:true, tags:['mustard','seeds','spice'] },
    { name:'Cumin Seeds (100 g)',          slug:'cumin-seeds-100g',           description:'Whole jeera with earthy fragrance. Used for tempering and flavouring dals.', price:90,   salePrice:80,  images:['https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=500&q=80'], category:scId, subCategory:'spices',          sellerId:s3, sellerName:'OrganicKo Pasal', stock:180, sku:'SC-CUM-001', rating:4.6, reviewCount:145, isFeatured:false, isActive:true, tags:['cumin','jeera','spice'] },
    { name:'Tomato Ketchup (500 g)',       slug:'tomato-ketchup-500g',        description:'Tangy and sweet tomato ketchup. A must-have condiment for momos and fries.', price:180,  salePrice:160, images:['https://images.unsplash.com/photo-1605789538467-f715d58e03f9?w=500&q=80'], category:scId, subCategory:'sauces-condiments', sellerId:s1, sellerName:'HariBazar', stock:220, sku:'SC-KET-001', rating:4.5, reviewCount:312, isFeatured:false, isActive:true, tags:['ketchup','sauce','condiment'] },
    { name:'Chilli Sauce (300 ml)',        slug:'chilli-sauce-300ml',         description:'Hot and tangy chilli sauce. The perfect dipping companion for momos and pakoras.', price:140, salePrice:125, images:['https://images.unsplash.com/photo-1605789538467-f715d58e03f9?w=500&q=80'], category:scId, subCategory:'sauces-condiments', sellerId:s1, sellerName:'HariBazar', stock:180, sku:'SC-CHS-001', rating:4.6, reviewCount:201, isFeatured:false, isActive:true, tags:['chilli sauce','sauce','hot'] },
    { name:'Soy Sauce (200 ml)',           slug:'soy-sauce-200ml',            description:'Dark, savoury soy sauce for stir-fries, fried rice and noodle dishes.', price:120,  salePrice:105, images:['https://images.unsplash.com/photo-1605789538467-f715d58e03f9?w=500&q=80'], category:scId, subCategory:'sauces-condiments', sellerId:s1, sellerName:'HariBazar', stock:150, sku:'SC-SOY-001', rating:4.4, reviewCount:134, isFeatured:false, isActive:true, tags:['soy sauce','sauce','asian'] },

    // ── Bakery & Bread ───────────────────────────────────────────────────
    { name:'Whole Wheat Bread (400 g)',    slug:'whole-wheat-bread-400g',     description:'Soft whole wheat sandwich bread baked fresh daily. No preservatives.', price:90,   salePrice:80,  images:['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&q=80'], category:bbId, subCategory:'breads',           sellerId:s1, sellerName:'HariBazar', stock:100, sku:'BB-WHB-001', rating:4.5, reviewCount:234, isFeatured:false, isActive:true, tags:['bread','wheat','bakery'] },
    { name:'Butter Croissant (Pack of 4)', slug:'butter-croissant-4pack',     description:'Flaky, buttery croissants baked fresh every morning. Melt-in-mouth goodness.', price:260,  salePrice:240, images:['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&q=80'], category:bbId, subCategory:'breads',           sellerId:s1, sellerName:'HariBazar', stock:60,  sku:'BB-CRO-001', rating:4.7, reviewCount:178, isFeatured:true,  isActive:true, tags:['croissant','bakery','breakfast'] },
    { name:'Multigrain Bread (400 g)',     slug:'multigrain-bread-400g',      description:'Hearty multigrain bread with seeds and oats. Nutritious and filling.', price:120,  salePrice:105, images:['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&q=80'], category:bbId, subCategory:'breads',           sellerId:s1, sellerName:'HariBazar', stock:80,  sku:'BB-MGB-001', rating:4.6, reviewCount:112, isFeatured:false, isActive:true, tags:['bread','multigrain','healthy'] },
    { name:'Chocolate Cake (500 g)',       slug:'chocolate-cake-500g',        description:'Rich moist chocolate sponge cake with chocolate ganache. Perfect for celebrations.', price:650,  salePrice:590, images:['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&q=80'], category:bbId, subCategory:'cakes-pastries',   sellerId:s1, sellerName:'HariBazar', stock:30,  sku:'BB-CCK-001', rating:4.8, reviewCount:145, isFeatured:true,  isActive:true, tags:['cake','chocolate','bakery'] },
    { name:'Fruit Pastry (2 pcs)',         slug:'fruit-pastry-2pcs',          description:'Soft vanilla sponge topped with fresh cream and seasonal fruits. A bakery classic.', price:180, salePrice:160, images:['https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500&q=80'], category:bbId, subCategory:'cakes-pastries',   sellerId:s1, sellerName:'HariBazar', stock:50,  sku:'BB-FPS-001', rating:4.5, reviewCount:98,  isFeatured:false, isActive:true, tags:['pastry','cream','bakery'] },
    { name:'Sel Roti (6 pcs)',             slug:'sel-roti-6pcs',              description:'Traditional Nepali rice doughnut. Crispy outside, soft inside. Festive favourite.', price:180,  salePrice:160, images:['https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=500&q=80'], category:bbId, subCategory:'traditional-bakery', sellerId:s3, sellerName:'OrganicKo Pasal', stock:80,  sku:'BB-SEL-001', rating:4.9, reviewCount:312, isFeatured:true,  isActive:true, tags:['sel roti','nepali','traditional','bakery'] },
    { name:'Yomari (4 pcs)',               slug:'yomari-4pcs',                description:'Traditional Newari rice flour dumplings filled with chaku and sesame. Festive delicacy.', price:200, salePrice:180, images:['https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=500&q=80'], category:bbId, subCategory:'traditional-bakery', sellerId:s3, sellerName:'OrganicKo Pasal', stock:40,  sku:'BB-YOM-001', rating:4.8, reviewCount:89,  isFeatured:false, isActive:true, tags:['yomari','newari','traditional'] },

    // ── Oils & Ghee ──────────────────────────────────────────────────────
    { name:'Pure Cow Ghee (500 ml)',       slug:'pure-cow-ghee-500ml',        description:'Traditionally churned cow ghee. Golden colour, rich aroma. Ideal for dal and kheer.', price:850,  salePrice:799, images:['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&q=80'], category:ogId, subCategory:'ghee-butter',     sellerId:s3, sellerName:'OrganicKo Pasal', stock:100, sku:'OG-GHE-001', rating:4.9, reviewCount:423, isFeatured:true,  isActive:true, tags:['ghee','cow','organic'] },
    { name:'Organic Cow Ghee (250 ml)',    slug:'organic-cow-ghee-250ml',     description:'Small-batch organic ghee made from grass-fed cow milk. Purest quality.', price:480, salePrice:440, images:['https://images.unsplash.com/photo-1593759608142-e976bfe89e4e?w=500&q=80'], category:ogId, subCategory:'ghee-butter',     sellerId:s3, sellerName:'OrganicKo Pasal', stock:80,  sku:'OG-OGH-001', rating:4.9, reviewCount:167, isFeatured:false, isActive:true, tags:['ghee','organic','premium'] },
    { name:'Mustard Oil (1 litre)',        slug:'mustard-oil-1l',             description:'Cold-pressed mustard oil with a sharp, pungent taste. A Nepali kitchen essential.', price:320,  salePrice:295, images:['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&q=80'], category:ogId, subCategory:'cooking-oils',    sellerId:s1, sellerName:'HariBazar', stock:180, sku:'OG-MSO-001', rating:4.6, reviewCount:267, isFeatured:false, isActive:true, tags:['mustard oil','cooking oil','oil'] },
    { name:'Sunflower Oil (1 litre)',      slug:'sunflower-oil-1l',           description:'Light and healthy refined sunflower oil. Low in saturated fat, ideal for daily cooking.', price:280,  salePrice:255, images:['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&q=80'], category:ogId, subCategory:'cooking-oils',    sellerId:s1, sellerName:'HariBazar', stock:220, sku:'OG-SFO-001', rating:4.5, reviewCount:198, isFeatured:false, isActive:true, tags:['sunflower oil','cooking oil','oil'] },
    { name:'Coconut Oil (500 ml)',         slug:'coconut-oil-500ml',          description:'Virgin cold-pressed coconut oil. Multi-purpose — cooking, hair and skin care.', price:450,  salePrice:410, images:['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&q=80'], category:ogId, subCategory:'cooking-oils',    sellerId:s3, sellerName:'OrganicKo Pasal', stock:120, sku:'OG-CCO-001', rating:4.7, reviewCount:156, isFeatured:false, isActive:true, tags:['coconut oil','oil','organic'] },
    { name:'Olive Oil Extra Virgin (250 ml)', slug:'olive-oil-extra-virgin-250ml', description:'Premium extra virgin olive oil imported for salads and low-heat cooking.', price:680,  salePrice:620, images:['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&q=80'], category:ogId, subCategory:'cooking-oils',    sellerId:s3, sellerName:'OrganicKo Pasal', stock:80,  sku:'OG-OLO-001', rating:4.8, reviewCount:112, isFeatured:false, isActive:true, tags:['olive oil','oil','healthy'] },
  ].map(p => ({ ...p, createdAt:new Date(), updatedAt:new Date() }));

  const pr = await db.collection('products').insertMany(prods);
  console.log(`  ✅ ${pr.insertedCount} products`);

  await client.close();

  console.log('\n' + '='.repeat(60));
  console.log('✅ All done! Login credentials:\n');
  console.log('   👑 Admin:   admin@bazzar.com    / Admin@1234');
  console.log('   🛒 Buyer:   ram@example.com     / Buyer@1234');
  console.log('   🏪 Seller1: seller1@bazzar.com  / Seller@1234');
  console.log('   🏪 Seller2: seller2@bazzar.com  / Seller@1234');
  console.log('   🏪 Seller3: seller3@bazzar.com  / Seller@1234\n');
}

main().catch(e => { console.error('❌', e.message); process.exit(1); });
